spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gu?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Shanghai
    username: root
    password: 12345
  activiti:
    database-schema: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

